### PR TITLE
Build-CLI: Refactoring & Suggestions for Tracker UI

### PR DESCRIPTION
**Pull request by AmmarAbouZor**
This PR still a work in progress, since it has some suggestions that I would like to discuss... 

**Implemented Points:**
- [x] Rewrite jobs alignment to keep the braces and the symbols in the same horizontal alignment among all lines.
- [x] Little refactoring to write the progress line in one print call. 
- [x] Small refactoring to get the length or max using  `unwrap_or`.
- [ ] Use progress bar as working indicator.

**Suggestion:**
I think if we used the status bar as working indicator that moves up and down while the job is in progress would give a more responsive look to the app. I can implement that using a timer and the `select!` macro in inside the `run()` method of the `tracker` struct.

@DmitryAstafyev Do you think it would be better to keep an indicator moving while the job is in progress or it's better to keep the bar as progress bar?

### CODE REVIEW

**Comment by AmmarAbouZor** [comment]
@DmitryAstafyev  I've changed the placeholder here from zero to spaces, but this easily changeable. Here is two screenshots for each option 

Screenshot from 2023-12-04 20-36-34
Screenshot from 2023-12-04 20-36-05

**Comment by DmitryAstafyev** [comment]
hello @AmmarAbouZor sorry for the late response, I was busy with other stuff. Thanks much for your PRs, I will take a look on it this week.
Thanks much!

**Comment by DmitryAstafyev** [comment]
Hello @AmmarAbouZor 

> I think if we used the status bar as working indicator that moves up and down while the job is in progress would give a more responsive look to the app. I can implement that using a timer and the select! macro in inside the run() method of the tracker struct.

There is already a progress bar for each running job. Do you want to add some global one?

**Comment by DmitryAstafyev** [comment]
@AmmarAbouZor if you want you can take a look to tasks related to wasm... it's still missed. I am talking about this part of application: `application/apps/rustcore/wasm-bindings`
It also should be included into linting and testing workflows

**Comment by AmmarAbouZor** [comment]
> There is already a progress bar for each running job. Do you want to add some global one?

My suggestion is to not use these progress bars as progress indicators, but as "Task is running" indicator. So the progress bar will be in continues movement as long as the task is running, like the second example of [indicatif](https://github.com/console-rs/indicatif). But in our case we still can use the vertical bar but we let it in continues movement up and down until the task is done.

**Comment by AmmarAbouZor** [comment]
> @AmmarAbouZor if you want you can take a look to tasks related to wasm... it's still missed. I am talking about this part of application: `application/apps/rustcore/wasm-bindings` It also should be included into linting and testing workflows

Thanks for the suggestion, I'll look into that in the holidays and maybe create another PR for them :+1:

**Comment by AmmarAbouZor** [comment]
> > There is already a progress bar for each running job. Do you want to add some global one?
> 
> My suggestion is to not use these progress bars as progress indicators, but as "Task is running" indicator. So the progress bar will be in continues movement as long as the task is running, like the second example of [indicatif](https://github.com/console-rs/indicatif). But in our case we still can use the vertical bar but we let it in continues movement up and down until the task is done.

I think my suggestion is already implemented in the current state. Currently the progress bars are incremented each time their stdout is getting new data, which indicates that work is in progress.

We can still automate the call of `TRACKER.progress()` with a timer which will give an animated movement to each progress bar, but this could give fake positive if the stdout isn't emitting any new data but the the bars are still moving. Therefore I think we can leave it as it's current implementation for now.

**Comment by AmmarAbouZor** [comment]
I think this PR is ready to be reviewed since the current implementation of the progress indicator is the one that we will go with :+1:

**Pull request merged**
